const loader=document.querySelector('#loader'), bar=document.querySelector('#progressBar'), number=document.querySelector('#progressNumber'), text=document.querySelector('#loadText'), main=document.querySelector('#mainContent');
const lines=['Locating the birthday girlie...','Loading premium memories...','Calculating meows per minute...','Applying pink sparkles...','Birthday universe ready ✦'];let p=0;
const loading=setInterval(()=>{p+=Math.ceil(Math.random()*7);if(p>100)p=100;bar.style.width=p+'%';number.textContent=p+'%';text.textContent=lines[Math.min(Math.floor(p/23),4)];if(p===100){clearInterval(loading);setTimeout(()=>{loader.style.opacity=0;setTimeout(()=>{loader.remove();main.classList.remove('hidden');observe();typeLetter()},750)},450)}},85);

function observe(){const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>ob.observe(el))}

const letter=`Jokes aside, you make ordinary days more memorable and every ridiculous moment ten times funnier. Thank you for listening to the nonsense, joining the chaos and being exactly the kind of person the world needs more of.\n\nI hope this new year of your life feels soft when it needs to, exciting when you want it to, and full of people and moments that remind you how loved you are. Happy birthday, Meow. Never stop being wonderfully, loudly, unapologetically you.`;
function typeLetter(){const target=document.querySelector('#typedLetter');let i=0;const io=new IntersectionObserver(es=>{if(es[0].isIntersecting&&!target.dataset.started){target.dataset.started='1';const timer=setInterval(()=>{target.textContent+=letter[i++]||'';if(i>=letter.length)clearInterval(timer)},19)}},{threshold:.3});io.observe(target)}

// Original browser-generated ambient melody. No external or copyrighted audio file is used.
let audioCtx,master,playing=false,timer;const musicBtn=document.querySelector('#musicBtn'),musicLabel=document.querySelector('#musicLabel');
function note(freq,start,duration){const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.055,start+.05);gain.gain.exponentialRampToValueAtTime(.001,start+duration);osc.connect(gain).connect(master);osc.start(start);osc.stop(start+duration)}
function melody(){if(!playing)return;const now=audioCtx.currentTime+.05,notes=[261.63,329.63,392,493.88,440,392,329.63,293.66];notes.forEach((n,i)=>note(n,now+i*.38,.65));timer=setTimeout(melody,notes.length*380)}
musicBtn.addEventListener('click',()=>{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.9;master.connect(audioCtx.destination)}playing=!playing;musicBtn.classList.toggle('playing',playing);musicLabel.textContent=playing?'pause the vibe':'play the vibe';if(playing){audioCtx.resume();melody()}else{clearTimeout(timer);audioCtx.suspend()}});

document.querySelectorAll('#choices button').forEach(btn=>btn.addEventListener('click',()=>{const result=document.querySelector('#quizResult');if(btn.dataset.correct==='true'){result.textContent='Correct. The research is conclusive. ✦';burst(40)}else{result.textContent='Interesting theory. Unfortunately, the answer is Meow Meow.'}}));
document.querySelector('#surpriseBtn').addEventListener('click',e=>{e.target.style.display='none';document.querySelector('#finalMessage').classList.remove('hidden');burst(160)});
function burst(count){const colors=['#ff6fa5','#ffd166','#cab7ff','#fff8f2','#f04484'];for(let i=0;i<count;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.width=5+Math.random()*9+'px';c.style.height=7+Math.random()*12+'px';c.style.background=colors[Math.floor(Math.random()*colors.length)];c.style.animationDuration=2.5+Math.random()*3+'s';c.style.animationDelay=Math.random()*.5+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),6500)}}

const canvas=document.querySelector('#sparkleCanvas'),ctx=canvas.getContext('2d');let stars=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars=Array.from({length:Math.min(100,innerWidth/10)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.6+.2,a:Math.random(),v:Math.random()*.015+.004}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);stars.forEach(s=>{s.a+=s.v;if(s.a>1||s.a<.15)s.v*=-1;ctx.globalAlpha=s.a;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
