const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const loader=$('#loader'),bar=$('#progressBar'),num=$('#progressNumber'),loadText=$('#loadText');let p=0;const lines=['Locating the birthday girlie...','Loading premium memories...','Calculating meows per minute...','Applying pink sparkles...','Birthday universe ready ✦'];function show(){if(loader){loader.style.opacity=0;setTimeout(()=>loader.remove(),700)}typeLetter()}if(loader&&bar&&num){const t=setInterval(()=>{p=Math.min(100,p+6);bar.style.width=p+'%';num.textContent=p+'%';loadText.textContent=lines[Math.min(4,Math.floor(p/23))];if(p===100){clearInterval(t);setTimeout(show,300)}},80);setTimeout(show,5000)}else show();
const letter=`Baki sab thikee, Happiiestt bdayy meoww meoww, abhi just it was 11.11 some mins ago, thank you for always being there, likhneko bahot kuch hainn, i will call wo baat alag hainn 😅, bhetuya...`;function typeLetter(){const el=$('#typedLetter');if(!el||el.dataset.on)return;el.dataset.on=1;let i=0;const t=setInterval(()=>{el.textContent+=letter[i++]||'';if(i>=letter.length)clearInterval(t)},24)}
const musicBtn=$('#musicBtn'),musicLabel=$('#musicLabel'),music=$('#bgMusic');if(musicBtn&&music){music.volume=.6;musicBtn.onclick=async()=>{try{if(music.paused){await music.play();musicBtn.classList.add('playing');musicLabel.textContent='pause the vibe'}else{music.pause();musicBtn.classList.remove('playing');musicLabel.textContent='play the vibe'}}catch(e){console.error(e);musicLabel.textContent='music failed'}}}
function burst(n){const colors=['#ff6fa5','#ffd166','#cab7ff','#fff8f2'];for(let i=0;i<n;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.width=5+Math.random()*9+'px';c.style.height=7+Math.random()*12+'px';c.style.background=colors[i%colors.length];c.style.animationDuration=2+Math.random()*3+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),5500)}}
$$('#choices button').forEach(b=>b.onclick=()=>{const r=$('#quizResult');r.textContent='Correct. The research is conclusive. ✦';burst(35)});const surprise=$('#surpriseBtn');if(surprise)surprise.onclick=()=>{surprise.remove();$('#finalMessage').classList.remove('hidden');burst(150)};
const catBtn=$('#catBtn');function releaseCats(n=10){const a=['🐈','🐈‍⬛','🐱','😸','😼','✨','💗'];for(let i=0;i<n;i++){const c=document.createElement('span');c.className='pop-cat';c.textContent=a[Math.floor(Math.random()*a.length)];c.style.left=Math.random()*90+'vw';c.style.bottom='-70px';c.style.animationDelay=Math.random()*.6+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),4000)}}if(catBtn)catBtn.onclick=()=>releaseCats(12);
const target=new Date(2026,9,3);function countdown(){const els=['days','hours','minutes','seconds'].map(id=>$('#'+id));if(els.some(x=>!x))return;const d=target-new Date();if(d<=0){$('#countdownTitle').textContent='The Birthday Era is officially here! 🎂';els.forEach(x=>x.textContent='00');return}els[0].textContent=String(Math.floor(d/86400000)).padStart(2,'0');els[1].textContent=String(Math.floor(d/3600000)%24).padStart(2,'0');els[2].textContent=String(Math.floor(d/60000)%60).padStart(2,'0');els[3].textContent=String(Math.floor(d/1000)%60).padStart(2,'0')}countdown();setInterval(countdown,1000);
let audioCtx,master;$$('.drum').forEach((d,i)=>d.onclick=()=>{try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.connect(audioCtx.destination)}const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.frequency.setValueAtTime(+d.dataset.note,n);o.frequency.exponentialRampToValueAtTime(70,n+.25);g.gain.setValueAtTime(.2,n);g.gain.exponentialRampToValueAtTime(.001,n+.3);o.connect(g).connect(master);o.start();o.stop(n+.31);$('#beatCaption').textContent=i?'midnight meow beat ✦':'pink birthday beat ♡';burst(12)}catch(e){console.error(e)}});
let lock=false;function paw(x,y){if(lock)return;lock=true;const p=document.createElement('span');p.className='paw-print';p.textContent='🐾';p.style.left=x+'px';p.style.top=y+'px';document.body.appendChild(p);setTimeout(()=>p.remove(),2100);setTimeout(()=>lock=false,180)}addEventListener('pointermove',e=>{if(e.pointerType==='mouse')paw(e.clientX,e.clientY)});const gift=$('#giftBox');if(gift)gift.onclick=()=>{gift.remove();$('#giftReveal').classList.remove('hidden');releaseCats(15);burst(100)};
const canvas=$('#sparkleCanvas'),ctx=canvas&&canvas.getContext('2d');let stars=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars=Array.from({length:70},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.3,a:Math.random()}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);stars.forEach(s=>{s.a=.2+Math.abs(Math.sin(Date.now()/900+s.x));ctx.globalAlpha=s.a;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()});requestAnimationFrame(draw)}if(canvas&&ctx){resize();draw();addEventListener('resize',resize)}
